language: node_js

node_js:
  - 12

cache: yarn

install:
  - yarn
script:
  - yarn test
  - yarn build

jobs:
  include:
    - stage: general
      if: branch = development AND commit_message !~ /\[skip publish\]/

      before_deploy:
        - yarn bump-version:prerelease
        - yarn build

      deploy:
        - provider: npm
          email: $NPM_EMAIL
          api_key: $NPM_TOKEN
          skip_cleanup: true
          on:
            branch: development
          tag: next

    - stage: general
      if: branch = master AND commit_message !~ /\[skip publish\]/

      before_deploy:
        - >
          if ! [ "${BEFORE_DEPLOY_RUN}" ]; then
            export BEFORE_DEPLOY_RUN=1;
            git config user.email "builds@travis-ci.com"
            git config user.name "Travis CI"
            yarn bump-version
            git push --verbose --no-verify --follow-tags ${OWNER}${GH_TOKEN}@${GH_REF} HEAD:master
            yarn build
          fi
      deploy:
        - provider: pages
          github_token: $GH_TOKEN
          skip_cleanup: true
          keep_history: true
          local_dir: docs-dist
          on:
            branch: master

        - provider: npm
          email: $NPM_EMAIL
          api_key: $NPM_TOKEN
          skip_cleanup: true
          keep_history: true
          on:
            branch: master
